/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElAutocompleteFetchElAutocompleteRef_no: typeof import('element-plus/es')['ElAutocompleteFetchElAutocompleteRef_no']
  const ElAutocompleteFetchSuggestionsRef_no: typeof import('element-plus/es')['ElAutocompleteFetchSuggestionsRef_no']
  const ElInputCopy: typeof import('element-plus/es')['ElInputCopy']
  const ElLoading: typeof import('element-plus/es')['ElLoading']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElSelectCopy: typeof import('element-plus/es')['ElSelectCopy']
}
